### ISSUE TITLE
direct download crash on Android 10

### ISSUE THREAD

**Issue by WhatTheBlock** [SirLordPouya/AndroidAppUpdater#3]
<pre><code>java.lang.IllegalStateException: Not one of standard directories: /ApkUpdate
        at android.os.Parcel.createException(Parcel.java:2079)
        at android.os.Parcel.readException(Parcel.java:2039)
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:188)
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:140)
        at android.content.ContentProviderProxy.call(ContentProviderNative.java:658)
        at android.content.ContentProviderClient.call(ContentProviderClient.java:558)
        at android.content.ContentProviderClient.call(ContentProviderClient.java:546)
        at android.app.DownloadManager$Request.setDestinationInExternalPublicDir(DownloadManager.java:576)
        at ir.heydarii.appupdater.directlink.DirectLinkDownload.downloadApk(DirectLinkDownload.kt:115)
        at ir.heydarii.appupdater.directlink.DirectLinkDownload.getApk(DirectLinkDownload.kt:93)
        at ir.heydarii.appupdater.AppUpdaterDialog.onListListener(AppUpdaterDialog.kt:169)
        at ir.heydarii.appupdater.AppUpdaterDialog.access$onListListener(AppUpdaterDialog.kt:35)
        at ir.heydarii.appupdater.AppUpdaterDialog$setUpBothRecyclers$2.invoke(AppUpdaterDialog.kt:119)
        at ir.heydarii.appupdater.AppUpdaterDialog$setUpBothRecyclers$2.invoke(AppUpdaterDialog.kt:35)
        at ir.heydarii.appupdater.DirectRecyclerAdapter$SoresViewHolder$onBind$1.onClick(DirectRecyclerAdapter.kt:39)</code></pre>

**Comment by SirLordPouya** [comment]
Hi
It must be fixed in version 4.0.0. so I'm closing this issue.
Please reopen it if you see this happen again.
Thanks
